### ISSUE TITLE
[dev_mvp] Login screen states "privacy by" - missing word?

### ISSUE THREAD

**Issue by AdamLeonSmith** [Path-Check/safeplaces-frontend#41]
![image](https://user-images.githubusercontent.com/48051844/80715465-4d2f0c80-8aee-11ea-9f30-36bcbe5d11db.png)

**Comment by mundanelunacy** [comment]
formatting issues caused because branding assets are missing in config.js
https://github.com/Path-Check/safeplaces-frontend/blob/dev_mvp/js/config.js

@penrods 
https://vault.tripleblind.app/ looks like it's been taken down
Could you provide a spec for these assets (i.e. width size, max text length)
Probably sufficient to just add that to the config file
