### ISSUE TITLE
[dev_mvp] Login button renders outside of the expected area

### ISSUE THREAD

**Issue by AdamLeonSmith** [Path-Check/safeplaces-frontend#42]
![image](https://user-images.githubusercontent.com/48051844/80715529-5e781900-8aee-11ea-9d74-531920d1e196.png)

**Comment by AdamLeonSmith** [comment]
Note - Chrome browser

**Comment by mundanelunacy** [comment]
formatting issues caused because branding assets are missing in config.js
https://github.com/Path-Check/safeplaces-frontend/blob/dev_mvp/js/config.js

@penrods 
https://vault.tripleblind.app/ looks like it's been taken down
Could you provide a spec for these assets (i.e. width size, max text length)
Probably sufficient to just add that to the config file
